namespace FastCopy
{
    [bindable]
    [default_interface]
    runtimeclass AnimatedValue : Microsoft.UI.Xaml.DependencyObject
    {
        AnimatedValue();

        Double Value{ get; set; };
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };
    }
}
