import "FileInfoViewModel.idl";

namespace FastCopy
{
    [default_interface]
    runtimeclass ConfirmDeleteFileWindow : Microsoft.UI.Xaml.Window
    {
        ConfirmDeleteFileWindow();
        
        String FilePath{ get; };

        static String TypeDescription{ get; };

        static String SizeDescription{ get; };

        static String DateDescription{ get; };
        FileInfoViewModel FileInfo{ get; };
    }
}
