namespace FastCopy
{
    [default_interface]
    runtimeclass ConfirmDeleteFileWindow : Microsoft.UI.Xaml.Window
    {
        ConfirmDeleteFileWindow();
        
        String FileName{ get; };
    }
}
