namespace FastCopy
{
    [default_interface]
    runtimeclass ConfirmDeleteMultipleItemsWindow : Microsoft.UI.Xaml.Window
    {
        ConfirmDeleteMultipleItemsWindow();
        
        String ItemCountText{ get; };
    }
}
