import "RobocopyViewModel.idl";
import "ProgressBarEx.idl";

namespace FastCopy
{
    [default_interface]
    runtimeclass CopyDialog : Microsoft.UI.Xaml.Controls.Page
    {
        CopyDialog();
        RobocopyViewModel ViewModel{ get; };
        FastCopy.ProgressBarEx ProgressBar{ get; };

        Microsoft.UI.Xaml.Controls.Grid MainPanel{ get; };
    }
}
