import "RobocopyViewModel.idl";

namespace FastCopy
{
    [default_interface]
    runtimeclass CopyDialogWindow : WinUI3Package.WindowEx
    {
        CopyDialogWindow();
        
        RobocopyViewModel ViewModel{ get; };
    }
}
