import "RobocopyViewModel.idl";

//Do not combine CopyDialog into CopyDialogWindow, this causes compilation error
namespace FastCopy
{
    [default_interface]
    runtimeclass CopyDialog : Microsoft.UI.Xaml.Controls.Page
    {
        CopyDialog();
        RobocopyViewModel ViewModel{ get; };

        static Double PercentConvert(Double value);
        static String GetTextFromKeyboardAccelerators(Windows.Foundation.Collections.IVector<Microsoft.UI.Xaml.Input.KeyboardAccelerator> keys);
    }
}
