// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace FastCopy
{
    [default_interface]
    runtimeclass CopyDialogWindow : WinUI3Package.WindowEx
    {
        CopyDialogWindow();
    }
}
