import "XCopyViewModel.idl";

namespace FastCopy
{
    [default_interface]
    runtimeclass CopyDialog : Microsoft.UI.Xaml.Controls.Page
    {
        CopyDialog();
        FastCopy.XCopyViewModel ViewModel{ get; };
    }
}
