namespace FastCopy
{

    enum ExplorerItemType
    {
        Folder,
        File
    };

    enum ItemStatus
    {
        Pending,   //IsIndeterminate=>True
        Paused,     //IsIndeterminate=>True IsPaused=>True
        Executing,  //IsIndeterminate=>False, set its Value
        Failed      //IsIndeterminate=>True ShowError=>True
    };

    [bindable]
    [default_interface]
    runtimeclass ExplorerItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ExplorerItem(String name, ExplorerItemType type);
        ExplorerItem(Windows.Storage.StorageFile file);
        ExplorerItem(Windows.Storage.StorageFolder folder, Boolean recurse, Int32 level);
        
        ExplorerItemType Type{ get; set; };
        
        Windows.Foundation.Collections.IObservableVector<ExplorerItem> Children{ get; };
        String Name{ get; set; };

        String FileName{ get; };

        Boolean IsFinished{ get; set; };
        Boolean IsFailed{ get; set; };

        UInt64 Size{ get; };

        Windows.Foundation.IAsyncAction OpenLocation();

        //Status related

        String CurrentFile{ get; };

        Double Progress{ get; }; //0~100 double value
        UInt64 SizeRemain{ get; };
        UInt32 SecondsRemain{ get; };
    }
}
