namespace FastCopy
{
    struct ExtendedFileInfo
    {
        String name;
        String value;
    };

    [bindable]
    [default_interface]
    runtimeclass FileInfoViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        FileInfoViewModel(String path);
        
        String Path{ get; };
        String Filename{ get; };
        
        /*file times */
        Windows.Foundation.DateTime CreateTime{ get; };
        Windows.Foundation.DateTime LastAccessTime{get; };
        Windows.Foundation.DateTime LastWriteTime{get; };

        UInt64 Bytes{ get; };
        Boolean Selected;

        /*Tooltip*/
        Windows.Foundation.Collections.IVector<Object> tooltipInfo{get; };


        Microsoft.UI.Xaml.Media.ImageSource Bitmap{ get; };

        event Windows.Foundation.EventHandler<Boolean> SelectionChanged;
    }
}
