import "ICopyBase.idl";
import "FileCompareViewModel.idl";

namespace FastCopy
{
    /*[bindable]*/
    [Microsoft.UI.Xaml.Data.Bindable]
    [default_interface]
    runtimeclass RobocopyViewModel : ICopyBase
    {
        RobocopyViewModel();
        
        String RecordFile;
        String SizeText{ get; };

        Windows.Foundation.Uri DestinationUri{ get; };

        /*Duplicate files*/
        Windows.Foundation.Collections.IObservableVector<FastCopy.FileCompareViewModel> DuplicateFiles{ get; };
        Windows.Foundation.IReference<Boolean> UseSource;
        Windows.Foundation.IReference<Boolean> UseDestination;

        //Confirm duplicate list
        void ConfirmDuplicates();

        Windows.Foundation.IAsyncOperation<UInt64> GetTotalSize();
    }
}
