import "ICopyBase.idl";
import "FileCompareViewModel.idl";

namespace FastCopy
{
    [bindable]
    [default_interface]
    runtimeclass RobocopyViewModel : ICopyBase
    {
        RobocopyViewModel();
        
        String RecordFile;
        String SizeText{ get; };

        Windows.Foundation.Uri DestinationUri{ get; };

        Windows.Foundation.Collections.IObservableVector<FastCopy.FileCompareViewModel> DuplicateFiles{ get; };
    }
}
