namespace FastCopy
{
    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel 
        : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsViewModel();

        Boolean Notify;
        Int32 MultipleWindowBehavior;
        Int32 ThemeSelection;
        Int32 BackgroundSelection;
        Boolean DevMode;
        Boolean LoggerEnabled;
        Int32 LoggerVerbosity;
        Boolean LogDBEnabled;
        Int32 LogDBMinVerbositySelectedIndex;
    }
}
