namespace FastCopy
{
    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsViewModel();

        Boolean Notify;
        Int32 RenameBehavior;
        String RenameSuffix;
        Int32 MultipleWindowBehavior;
        Int32 ThemeSelection;
        Int32 BackgroundSelection;
        Boolean DevMode;

        static Microsoft.UI.Xaml.Visibility IsRenameTextBoxVisible(Int32 renameBehavior);
    }
}
