// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace FastCopy
{
    [default_interface]
    runtimeclass SpeedGraph : Microsoft.UI.Xaml.Controls.UserControl
    {
        SpeedGraph();

        void SetTotal(UInt64 bytes);
        void AddPoint(UInt64 progressBytes, UInt64 speed);
        void SetSpeed(UInt64 speed);
        void SetSpeed(Double percent, UInt64 speed);

        void Pause();
        void Error();
    }
}
