namespace FastCopy
{
    [bindable]
    [default_interface]
    runtimeclass TaskbarControl : Microsoft.UI.Xaml.Controls.Control
    {
        TaskbarControl();
        
        Microsoft.UI.Xaml.Window Window;

        Double Value;
    }
}
