namespace FastCopy
{
    enum TaskbarState
    {
        NoProgress,
        Indeterminate,
        Normal,
        Error,
        Paused
    };

    [bindable]
    [default_interface]
    runtimeclass TaskbarControl : Microsoft.UI.Xaml.Controls.Control
    {
        TaskbarControl();
        
        Microsoft.UI.Xaml.Window Window;

        Double Value;
		TaskbarState State;
    }
}
